-- ============================================================================
-- ClubOps AI -- migrations 004 through 008, in order, as one script.
--
-- Generated by concatenating supabase/migrations/004..008. Paste the WHOLE
-- file into the Supabase SQL editor and run it once.
--
-- Safe to re-run: every statement is idempotent (create or replace / if not
-- exists / drop ... if exists). The 008 backfill only ever promotes.
--
-- Prerequisites: schema.sql, seed.sql, 002 and 003 are already applied.
-- ============================================================================


-- ==========================================================================
-- 004_tenant_rls.sql
--   Club-scoped RLS. THE critical one: without it any logged-in
--   user can read every club's rows through the anon key.
-- ==========================================================================

-- 004: club-scoped Row Level Security.
--
-- 002 scoped every policy by ROLE but never by CLUB: "auth read events" was
-- `using (true)`, and members/tasks/feedback/agent_actions all resolved to
-- `current_member_role() = 'leader'` -- true for a leader of ANY club. Since the
-- browser holds the anon key, one login could read every tenant's rows straight
-- off the PostgREST API.
--
-- Every policy below is anchored on current_club_id(). Run after 002/003.

-- ── Tenant anchor ──────────────────────────────────────────────────────
-- security definer so it can read `members` without recursing into members' RLS.
create or replace function public.current_club_id() returns uuid
language sql stable security definer set search_path = public as $$
  select club_id from members where auth_user_id = auth.uid()
$$;

revoke execute on function public.current_club_id() from public, anon;
grant  execute on function public.current_club_id() to authenticated;

-- ── Replace the role-only policies from 002 ────────────────────────────
drop policy if exists "auth read clubs"            on clubs;
drop policy if exists "auth read events"           on events;
drop policy if exists "leader all, member self"        on members;
drop policy if exists "leader all, member assigned"    on tasks;
drop policy if exists "leader all, member about self"  on feedback;
drop policy if exists "leader reads actions"           on agent_actions;

-- A user sees exactly one club: their own.
create policy "own club" on clubs for select to authenticated
  using (id = current_club_id());

create policy "own club" on events for select to authenticated
  using (club_id = current_club_id());

-- Club first, then role. A leader of club A is not a leader of club B.
create policy "own club, scoped by role" on members for select to authenticated
  using (
    club_id = current_club_id()
    and (current_member_role() = 'leader' or auth_user_id = auth.uid())
  );

create policy "own club, scoped by role" on tasks for select to authenticated
  using (
    exists (select 1 from events e where e.id = tasks.event_id
                                     and e.club_id = current_club_id())
    and (current_member_role() = 'leader' or assignee_id = current_member_id())
  );

create policy "own club, scoped by role" on feedback for select to authenticated
  using (
    exists (select 1 from events e where e.id = feedback.event_id
                                     and e.club_id = current_club_id())
    and (current_member_role() = 'leader' or subject_member_id = current_member_id())
  );

create policy "own club leaders" on agent_actions for select to authenticated
  using (
    current_member_role() = 'leader'
    and exists (select 1 from events e where e.id = agent_actions.event_id
                                         and e.club_id = current_club_id())
  );

-- meeting_notes and club_documents keep RLS on with NO policy: invisible to the
-- browser entirely. Only the backend's service key touches them.

-- The exists() subqueries above run per row; these keep them index-assisted.
create index if not exists idx_tasks_event_id    on tasks (event_id);
create index if not exists idx_feedback_event_id on feedback (event_id);

-- ── Verification ───────────────────────────────────────────────────────
-- Impersonate a user and confirm the counts are per-club, not global:
--   set local role authenticated;
--   set local request.jwt.claims = '{"sub":"<auth_user_id>","role":"authenticated"}';
--   select count(*) from events;   -- must be that club's count, not the global one
--
-- DOWN (manual): drop the six policies above and current_club_id(), then
-- re-create the policies from 002 section 5.


-- ==========================================================================
-- 005_tenant_identity.sql
--   Per-club email uniqueness + club_invites. Required by 008.
-- ==========================================================================

-- 005: make member identity tenant-scoped.
--
-- Two problems from schema.sql + 002:
--   1. `members.email text not null unique` is GLOBAL. One person cannot belong
--      to two clubs, and a signup whose address already exists in another
--      tenant hits a unique violation that handle_auth_user swallows -- leaving
--      an auth user with no member row and no error anywhere.
--   2. handle_auth_user dropped every new signup into
--      `(select id from clubs order by created_at limit 1)` -- i.e. whichever
--      club was created first. With more than one tenant, self-service signup
--      silently joins the wrong club.
--
-- Fix: uniqueness becomes (club_id, lower(email)), and club membership is
-- granted by an explicit invite rather than inferred. Run after 004.

-- ── 1. Email is unique within a club, not globally ─────────────────────
alter table members drop constraint if exists members_email_key;
drop index if exists members_email_key;

create unique index if not exists members_email_per_club
  on members (club_id, lower(email));

-- ── 2. Invites decide which club a new account joins ───────────────────
create table if not exists club_invites (
  email      text primary key check (email = lower(email)),
  club_id    uuid not null references clubs(id) on delete cascade,
  role       text not null default 'member' check (role in ('leader', 'member')),
  created_at timestamptz not null default now()
);
create index if not exists idx_club_invites_club on club_invites (club_id);

-- Backend-managed only: RLS on, no policy => invisible to the browser.
alter table club_invites enable row level security;

-- Keep every already-seeded, not-yet-claimed member reachable. Without this the
-- demo logins (priya@/dev@/alex@club.edu) could no longer link themselves.
insert into club_invites (email, club_id, role)
select lower(m.email), m.club_id, m.role
from members m
where m.auth_user_id is null
on conflict (email) do nothing;

-- ── 3. Signup handler ──────────────────────────────────────────────────
-- SECURITY, unchanged from 002 and still load-bearing: the role is NEVER read
-- from raw_user_meta_data (users control that field). It comes from the invite,
-- which only a leader can write. A pre-seeded row is still only claimed by an
-- account whose email is CONFIRMED, so nobody takes over a leader row by
-- signing up with their address.
create or replace function public.handle_auth_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  invite     club_invites%rowtype;
  existing   members%rowtype;
  club_count int;
begin
  if exists (select 1 from members where auth_user_id = new.id) then
    return new;
  end if;

  select * into invite from club_invites where email = lower(new.email);

  if not found then
    -- No invite. With exactly ONE club there is no ambiguity about which club
    -- this account belongs to, so open sign-up still works. With two or more,
    -- the club is genuinely unknowable from an email address and we must not
    -- guess -- guessing was the original bug (002 used
    -- `order by created_at limit 1`, silently joining whichever club existed
    -- first). Sign-up itself is never blocked either way: /dashboard already
    -- renders an "account not set up yet" state for a user with no member row.
    select count(*) into club_count from clubs;
    if club_count <> 1 then
      return new;
    end if;
    select id into invite.club_id from clubs limit 1;
    invite.role := 'member';  -- never from raw_user_meta_data; users control that
  end if;

  select * into existing from members
   where club_id = invite.club_id and lower(email) = lower(new.email);

  if found then
    if existing.auth_user_id is null and new.email_confirmed_at is not null then
      update members set auth_user_id = new.id where id = existing.id;
      delete from club_invites where email = lower(new.email);
    end if;
    return new;
  end if;

  if new.email_confirmed_at is null then
    return new;  -- the on_auth_user_confirmed trigger will finish the job
  end if;

  insert into members (club_id, full_name, email, role, auth_user_id)
  values (
    invite.club_id,
    coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1)),
    new.email,
    invite.role,
    new.id
  );
  delete from club_invites where email = lower(new.email);
  return new;
end $$;

-- Triggers are unchanged from 002; re-asserted here so this file is idempotent.
drop trigger if exists on_auth_user_created   on auth.users;
drop trigger if exists on_auth_user_confirmed on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_auth_user();
create trigger on_auth_user_confirmed
  after update of email_confirmed_at on auth.users
  for each row when (old.email_confirmed_at is null and new.email_confirmed_at is not null)
  execute function public.handle_auth_user();

-- ── Operating this ─────────────────────────────────────────────────────
-- While the project has exactly ONE club, open sign-up keeps working and you
-- need none of this. Invites become REQUIRED the moment a second club exists.
--
-- Invite someone into a specific club:
--   insert into club_invites (email, club_id, role)
--   values (lower('newmember@club.edu'), '<club uuid>', 'member');
--
-- Promote an existing member:
--   update members set role = 'leader' where id = '<member uuid>';
--
-- DOWN (manual): drop club_invites, drop index members_email_per_club, restore
-- `alter table members add constraint members_email_key unique (email)`, and
-- re-create handle_auth_user from 002 section 4.


-- ==========================================================================
-- 006_integrity_and_jobs.sql
--   plan_jobs table. REQUIRED -- 'Create event' 500s without it.
-- ==========================================================================

-- 006: referential integrity fixes + the planning job queue.
--
-- ON DELETE CASCADE was already correct almost everywhere (tasks.event_id,
-- feedback.event_id, agent_actions.event_id, meeting_notes.event_id,
-- events.club_id, members.club_id, club_documents.club_id). The defect is the
-- opposite: one cascade that destroys history. Run after 005.

-- ── 1. Deleting a member must not rewrite past event ratings ───────────
-- 002 made feedback.subject_member_id `on delete cascade`, so removing a
-- departed member DELETED every rating row naming them -- which fires
-- refresh_event_rating and silently moves the average_rating of every event
-- they were rated on. Ratings are historical facts: keep the row, drop the
-- link. (feedback.member_id, the author, is already `on delete set null`.)
alter table feedback drop constraint if exists feedback_subject_member_id_fkey;
alter table feedback
  add constraint feedback_subject_member_id_fkey
  foreign key (subject_member_id) references members(id) on delete set null;

-- Note on trg_feedback_rating: it stays `for each row`. It is correct as
-- written; the only bulk path is a cascade delete of an event's feedback, and
-- that recomputes the rating of an event that is itself being removed. A
-- statement-level rewrite with transition tables would need three separate
-- trigger functions and buys nothing at this scale.

-- ── 2. Planning jobs ───────────────────────────────────────────────────
-- /api/events/plan used to run a ~45s Gemini generation inside the request.
-- It now enqueues here and returns 202; the client polls. See
-- backend/app/routers/planning.py.
create table if not exists plan_jobs (
  id         uuid primary key default uuid_generate_v4(),
  club_id    uuid not null references clubs(id) on delete cascade,
  member_id  uuid references members(id) on delete set null,  -- who asked
  status     text not null default 'pending'
             check (status in ('pending', 'running', 'done', 'failed')),
  prompt     text not null,
  event_id   uuid references events(id) on delete set null,
  error      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_plan_jobs_club on plan_jobs (club_id, created_at desc);

-- Polled through FastAPI (which scopes by club), never read from the browser:
-- RLS on with no policy.
alter table plan_jobs enable row level security;

-- ── Verification ───────────────────────────────────────────────────────
-- Audit what actually cascades, so this never drifts again. confdeltype:
-- 'c' = cascade, 'n' = set null, 'a' = no action (a future orphan).
--
--   select c.conrelid::regclass as child, a.attname as col,
--          c.confrelid::regclass as parent, c.confdeltype as on_delete
--   from pg_constraint c
--   join unnest(c.conkey) k on true
--   join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k
--   where c.contype = 'f' and c.connamespace = 'public'::regnamespace
--   order by 1;
--
-- Any 'c' pointing at members from a historical table (feedback, agent_actions)
-- is a silent data-loss path and should be 'n'.


-- ==========================================================================
-- 007_rag_thresholds.sql
--   RAG relevance floor. REQUIRED -- knowledge queries fail without it.
-- ==========================================================================

-- 007: RAG relevance floor + vector index corrections. Run after 006.
--
-- Two problems in schema.sql:
--   1. match_club_documents took the top N neighbours with NO similarity
--      threshold, so a club with three retro docs answers a question about its
--      refund policy with the three least-unrelated chunks at similarity ~0.3 --
--      handed to the caller as authoritative context. Confident hallucination
--      with a citation attached.
--   2. `match_club_id is null` meant "search every club". That is the RAG-side
--      instance of the tenant leak fixed in 004, waiting for one caller to pass
--      null. The tenant is now required.

-- Signature changes (extra parameter), so the old overload must go first or
-- calls become ambiguous.
drop function if exists match_club_documents(vector(768), int, uuid);

create or replace function match_club_documents(
  query_embedding  vector(768),
  match_count      int   default 5,
  match_club_id    uuid  default null,
  min_similarity   float default 0.6
)
returns table (
  id uuid, source text, chunk_index int, content text,
  metadata jsonb, similarity float
)
language sql stable
as $$
  select id, source, chunk_index, content, metadata,
         1 - (embedding <=> query_embedding) as similarity
  from club_documents
  where match_club_id is not null           -- no wildcard: a null tenant matches nothing
    and club_id = match_club_id
    and 1 - (embedding <=> query_embedding) >= min_similarity
  order by embedding <=> query_embedding
  limit match_count;
$$;

-- ── Vector indexes ─────────────────────────────────────────────────────
-- club_documents already had HNSW with vector_cosine_ops -- correct, kept.
-- meeting_notes had `ivfflat ... with (lists = 100)` created in schema.sql at
-- schema-creation time, i.e. ON AN EMPTY TABLE. IVFFlat derives its centroids
-- from the rows present when the index is built; built on zero rows it
-- partitions near-randomly and silently returns poor neighbours forever, with
-- nothing in the system reporting the low recall. HNSW has no training step.
drop index if exists idx_notes_embedding;

-- Raise the build memory for this session so the build stays in RAM.
set maintenance_work_mem = '256MB';

create index if not exists idx_notes_embedding on meeting_notes
  using hnsw (embedding vector_cosine_ops) with (m = 16, ef_construction = 64);

-- On a table with live traffic, build these with CREATE INDEX CONCURRENTLY
-- instead -- which cannot run inside a transaction, so run it as its own
-- statement, not as part of this script.

-- Makes the club_id filter in match_club_documents index-assisted.
create index if not exists idx_club_documents_club_created
  on club_documents (club_id, created_at desc);

-- ── Verification ───────────────────────────────────────────────────────
-- Recall knob, set per session by the caller. Default 40; raise toward 100 for
-- recall, lower for latency:
--   set hnsw.ef_search = 40;
--
-- Confirm the index is actually used. A Seq Scan here means the operator class
-- and the query operator disagree -- both must be cosine (vector_cosine_ops
-- and <=>). Mixing in <-> (L2) silently bypasses the index:
--   explain analyze
--   select 1 - (embedding <=> '[...]'::vector(768))
--   from club_documents where club_id = '...'
--   order by embedding <=> '[...]'::vector(768) limit 5;
--
-- Tune min_similarity against YOUR corpus before launch. gemini-embedding-001
-- at 768 dims puts unrelated club prose around 0.45-0.55, so 0.6 is a
-- defensible starting point, not a measured one.


-- ==========================================================================
-- 008_signup_role_choice.sql
--   Leader/member choice at sign-up + backfill of existing accounts.
-- ==========================================================================

-- 008: let the person choose "leader" or "member" on the sign-up form.
-- Run after 005 (it uses club_invites).
--
-- ┌──────────────────────────────────────────────────────────────────────┐
-- │ DELIBERATE SECURITY TRADE-OFF -- chosen by the product owner.        │
-- │                                                                      │
-- │ 002 hard-coded role = 'member' and said, in capitals, that the role  │
-- │ must never be read from raw_user_meta_data, because that field is    │
-- │ controlled by the person signing up. This migration reverses that.   │
-- │                                                                      │
-- │ Consequence: anyone who can reach /signup can self-elect to          │
-- │ 'leader'. A leader can read every member, task and feedback row in   │
-- │ the club, delete feedback, and drive the agent's write tools. There  │
-- │ is NO verification step. This is acceptable for a closed demo and    │
-- │ is not acceptable once real club data is in the database.            │
-- │                                                                      │
-- │ To close it later, pick one and the rest of the app is unchanged:    │
-- │   a) leader access code -- add clubs.leader_code_hash, verify it     │
-- │      here before honouring 'leader';                                 │
-- │   b) approval -- insert as 'member' with a pending_role, and let an  │
-- │      existing leader promote;                                        │
-- │   c) revert to 005: delete the raw_user_meta_data branch below, so   │
-- │      only invites and the bootstrap rule can produce a leader.       │
-- └──────────────────────────────────────────────────────────────────────┘
--
-- Precedence, highest first:
--   1. An existing (seeded) member row  -> keeps whatever role it already has.
--   2. A club_invites row               -> the inviting leader's choice wins,
--                                          so an invite cannot be overridden
--                                          by what the invitee typed.
--   3. Bootstrap: club has no leader    -> this account becomes the leader.
--   4. The sign-up form's choice        -> 'leader' or anything else = 'member'.

create or replace function public.handle_auth_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  invite       club_invites%rowtype;
  existing     members%rowtype;
  club_count   int;
  leader_count int;
  target_club  uuid;
  target_role  text;
  requested    text;
begin
  if exists (select 1 from members where auth_user_id = new.id) then
    return new;
  end if;

  -- ── Which club? ──────────────────────────────────────────────────────
  select * into invite from club_invites where email = lower(new.email);
  if found then
    target_club := invite.club_id;
  else
    -- With exactly one club there is no ambiguity. With two or more the club
    -- is unknowable from an email address, so we refuse to guess.
    select count(*) into club_count from clubs;
    if club_count <> 1 then
      return new;
    end if;
    select id into target_club from clubs limit 1;
  end if;

  -- ── Claiming a pre-seeded row keeps that row's existing role ─────────
  -- Only an account with a CONFIRMED email may claim one, so nobody takes
  -- over a leader row just by signing up with their address.
  select * into existing from members
   where club_id = target_club and lower(email) = lower(new.email);
  if found then
    if existing.auth_user_id is null and new.email_confirmed_at is not null then
      update members set auth_user_id = new.id where id = existing.id;
      delete from club_invites where email = lower(new.email);
    end if;
    return new;
  end if;

  if new.email_confirmed_at is null then
    return new;  -- the on_auth_user_confirmed trigger will finish the job
  end if;

  -- ── Which role? ──────────────────────────────────────────────────────
  if invite.role is not null then
    target_role := invite.role;  -- an explicit grant by a leader outranks the form
  else
    -- UNVERIFIED, user-supplied. See the banner at the top of this file.
    requested := lower(nullif(trim(new.raw_user_meta_data->>'role'), ''));
    target_role := case when requested = 'leader' then 'leader' else 'member' end;
  end if;

  -- Bootstrap: a club with nobody in charge gets a leader regardless of what
  -- was asked for. Without this the first person into a fresh club could lock
  -- everyone out of the leader-only screens.
  select count(*) into leader_count
    from members where club_id = target_club and role = 'leader';
  if leader_count = 0 then
    target_role := 'leader';
  end if;

  insert into members (club_id, full_name, email, role, auth_user_id)
  values (
    target_club,
    coalesce(nullif(new.raw_user_meta_data->>'full_name', ''), split_part(new.email, '@', 1)),
    new.email,
    target_role,
    new.id
  );
  delete from club_invites where email = lower(new.email);
  return new;
end $$;

-- ── Backfill: accounts created before this migration ───────────────────
-- handle_auth_user only fires on insert/confirm, so anyone who already signed
-- up and picked "leader" is sitting in members with role = 'member' (002
-- discarded their choice). Apply retroactively what each of them actually
-- chose at sign-up. Promotes only; never demotes an existing leader.
update members m
   set role = 'leader'
  from auth.users u
 where u.id = m.auth_user_id
   and m.role <> 'leader'
   and lower(u.raw_user_meta_data->>'role') = 'leader';

-- ── Verification ───────────────────────────────────────────────────────
-- Who ended up with what, and how many leaders exist per club:
--   select c.name, m.email, m.role, m.auth_user_id is not null as linked
--   from members m join clubs c on c.id = m.club_id
--   order by c.name, m.role desc, m.email;
--
-- Demote someone who self-elected:
--   update members set role = 'member' where email = '...';


-- ==========================================================================
-- POST-RUN CHECK -- expect priya@club.edu, yugm@gmail.com, dani@gmail.com
-- to come back as 'leader'.
-- ==========================================================================
select email, role from members order by role desc, email;
